platform :ios, '8.0'
source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

xcodeproj 'UICollectionViewInteractiveMovementExample.xcodeproj'

pod 'UICollectionViewInteractiveMovement', :path => '../'
